### 1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,  
значение элемента с индексом (3,1) и второй столбец. Индексация  
начинается с нуля.

In [153]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример

Пример. Выполнить следующее:  
1. Создать вектор (одномерный массив) размера 10, заполненный  
нулями.
2. Создать вектор размера 10, заполненный единицами.  
3. Создать вектор размера 10, заполненный заданным числом.  
4. Создать вектор со значениями от 10 до 19.  

In [154]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум,  
максимум и среднее значение.

In [155]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.020725055618956878 0.99700353383366 0.4725527616186275


### 1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице  
местами.

In [156]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример

Выяснить результат следующих выражений:  
0 * np.nan  
np.nan == np.nan 
np.inf > np.nan  
np.nan - np.nan  
0.3 == 3 * 0.1

In [157]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример

Отсортировать массив.

In [158]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и  
единицами.

In [159]:
arr = np.zeros((8, 8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания  
необходимо использовать функцию arrange.

In [160]:
arr = np.arange(5)
arr = np.reshape(np.tile(arr, (5, 1)), (5, 5))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.

In [161]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.49722955 0.0864512  0.41432846]
  [0.30435162 0.0049495  0.92176657]
  [0.35721051 0.58561247 0.6759918 ]]

 [[0.46365263 0.69805659 0.08272941]
  [0.35287407 0.57828561 0.33180025]
  [0.73870787 0.46187609 0.03880285]]

 [[0.42895665 0.79225228 0.06804761]
  [0.19770048 0.04215429 0.17820363]
  [0.40152305 0.69896132 0.75397146]]]


### 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [162]:
arr = np.zeros((7, 7))
arr[0, :] = 1
arr[6, :] = 1
arr[:, 0] = 1
arr[:, 6] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [163]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr)[:: -1])

[8 7 6 5 4 3 2 1]


### 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [164]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 3)
9
2


### 2.2.1 Пример

Создать Series из списка Python, словаря Python, и массива Numpy  
(установить буквенные метки для последнего).

In [165]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


### 2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после  
третьего (во втором фрейме).

In [166]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3: ])

1
5
3    2
4    1
dtype: int64


### 2.2.3 Пример

Создайте новый фрейм данных.

In [167]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe ['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример

Загрузите фрейм данных по ссылке:  
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [168]:
# Создать URL адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

### 2.2.5 Пример

Пронализировать характеристики фрейма данных.

In [169]:
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


### 2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных.

In [170]:
dataframe.iloc[1: 4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### 2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого  
условия. Необходимо сформировать новый фрейм данных из пассажиров  
первого класса.

In [171]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### 2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не  
используя встроенную формулу.

In [172]:
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
# вычисляем разность между координатами точек a и b
diff = a - b
# возводим разность в квадрат и суммируем
sum_of_squares = np.sum(diff ** 2)
# вычисляем корень из суммы квадратов
distance = np.sqrt(sum_of_squares)
print(distance)

5.196152422706632


### 2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него  
фрейм данных (например, коллекцию фреймов данных можно найти  
здесь: https://github.com/akmand/datasets).

In [190]:
# Создать URL адрес
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer

### 3.2.1 Пример

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [187]:
# Загрузить библиотеки
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2 Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное  
отклонение 1.

In [186]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
print(standardized)

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение 1.0


### 3.2.3 Пример

Дан фрейм данных  
<pre>dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                    'B':[103.02,107.26,110.35,114.23,114.68],
                    'C':['big','small','big','small','small']})</pre>
Необходимо масштабировать его числовые столбцы.  

In [188]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A': [14.00, 90.20, 90.95, 96.27, 91.21],
                       'B': [103.02, 107.26, 110.25, 114.23, 114.68],
                       'C': ['big', 'small', 'big', 'small', 'small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.620069    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание

Загрузить фрейм данных по ссылке:  
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.  
Необходимо выполнить нормализацию первого числового признака  
(sepal_length_cm) с использованием минимаксного преобразования, а  
второго (sepal_width_cm) с задействованием z-масштабирования.

In [198]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# Создание URL адреса
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
# Загрузка данных
df = pd.read_csv(url)
# Нормализация первого признака (sepal_length_cm) с использованием минимаксного преобразования
scaler1 = MinMaxScaler()
df['sepal_length_cm'] = scaler1.fit_transform(df[['sepal_length_cm']])

# Задействование z-масштабирования для второго признака (sepal_width_cm)
scaler2 = StandardScaler()
df['sepal_width_cm'] = scaler2.fit_transform(df[['sepal_width_cm']])

# Вывод первых 5 строк фрейма данных
print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
